networks:
  edc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  manufacturer-edc-connector:
    build:
      context: ./edc-connector
    command: ["java", "-Dedc.keystore=certs/cert.pfx", "-Dedc.keystore.password=123456", "-Dedc.fs.config=configs/manufacturer.properties", "-jar", "connector.jar"]
    ports:
      - "11000:11000"
      - "11001:11001"
      - "11002:11002"
      - "11003:11003"
      - "11004:11004"
      - "11005:11005"
    volumes:
      - ./edc-connector/configs:/app/configs
    networks:
      edc-network:
        ipv4_address: 172.22.0.10



  recycler-edc-connector:
    build:
      context: ./edc-connector
    command: ["java", "-Dedc.keystore=certs/cert.pfx", "-Dedc.keystore.password=123456", "-Dedc.fs.config=configs/recycler.properties", "-jar", "connector.jar"]
    ports:
      - "12000:12000"
      - "12001:12001"
      - "12002:12002"
      - "12003:12003"
      - "12004:12004"
      - "12005:12005"
    volumes:
      - ./edc-connector/configs:/app/configs
    networks:
      edc-network:
        ipv4_address: 172.22.0.11


  supplier-edc-connector:
    build:
      context: ./edc-connector
    command: ["java", "-Dedc.keystore=certs/cert.pfx", "-Dedc.keystore.password=123456", "-Dedc.fs.config=configs/supplier.properties", "-jar", "connector.jar"]
    ports:
      - "13000:13000"
      - "13001:13001"
      - "13002:13002"
      - "13003:13003"
      - "13004:13004"
      - "13005:13005"
    volumes:
      - ./edc-connector/configs:/app/configs
    networks:
      edc-network:
        ipv4_address: 172.22.0.12

