networks:
  edc-network:
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  supplier-db-data:
  recycler-db-data:
  manufacturer-db-data:


services:

################ Database configuration:

  manufacturer-db:
    image: postgres:14
    environment:
      POSTGRES_DB: dpp_manufacturer
      POSTGRES_USER: dpp
      POSTGRES_PASSWORD: pass
    volumes:
      - manufacturer-db-data:/var/lib/postgresql/data
    networks:
      - edc-network


  recycler-db:
    image: postgres:14
    environment:
      POSTGRES_DB: dpp_recycler
      POSTGRES_USER: dpp
      POSTGRES_PASSWORD: pass
    volumes:
      - recycler-db-data:/var/lib/postgresql/data
    networks:
      - edc-network


  supplier-db:
    image: postgres:14
    environment:
      POSTGRES_DB: dpp_supplier
      POSTGRES_USER: dpp
      POSTGRES_PASSWORD: pass
    volumes:
      - supplier-db-data:/var/lib/postgresql/data
    networks:
      - edc-network






  ################ Running module + corresponding connector in the same container:

  manufacturer-with-connector:
    build:
      dockerfile: ./manufacturer/Dockerfile
    container_name: manufacturer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://manufacturer-db:5432/dpp_manufacturer
      SPRING_DATASOURCE_USERNAME: dpp
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
      - "10005:10005"
      - "127.0.0.1:8080:8080" # PS: ONLY USED FOR DEMONSTRATING
      #- "8080:8080" # PS: ONLY USED FOR DEMONSTRATING
    volumes:
      - ./edc-connector/configs:/app/configs
    networks:
      edc-network:
        ipv4_address: 172.22.0.10
    depends_on:
      - manufacturer-db


  recycler-edc-connector:
    build:
      dockerfile: ./recycler/Dockerfile
    container_name: recycler
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://recycler-db:5432/dpp_recycler
      SPRING_DATASOURCE_USERNAME: dpp
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "11000:11000"
      - "11001:11001"
      - "11002:11002"
      - "11003:11003"
      - "11004:11004"
      - "11005:11005"
      - "127.0.0.1:8081:8081" # PS: ONLY USED FOR DEMONSTRATING
      #- "8081:8081" # PS: ONLY USED FOR DEMONSTRATING
    volumes:
      - ./edc-connector/configs:/app/configs
    networks:
      edc-network:
        ipv4_address: 172.22.0.11
    depends_on:
      - recycler-db


  supplier-with-connector:
    build:
      dockerfile: ./supplier/Dockerfile
    container_name: supplier
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://supplier-db:5432/dpp_supplier
      SPRING_DATASOURCE_USERNAME: dpp
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "13000:13000"
      - "13001:13001"
      - "13002:13002"
      - "13003:13003"
      - "13004:13004"
      - "13005:13005"
      - "127.0.0.1:8083:8083" # PS: ONLY USED FOR DEMONSTRATING
      #- "8082:8082" # PS: ONLY USED FOR DEMONSTRATING
    volumes:
      - ./edc-connector/configs:/app/configs
    networks:
      edc-network:
        ipv4_address: 172.22.0.13
    depends_on:
      - supplier-db